repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: pytest -m unit
        language: python
        additional_dependencies:
          - pytest>=8,<9
        pass_filenames: false
