replicaCount: 1

image:
  repository: finsre
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  enabled: false
  type: ClusterIP
  port: 80

env:
  FINSRE_ENVIRONMENT: kubernetes
  FINSRE_GCP_BILLING_ACCOUNT: ""
  FINSRE_GCP_BILLING_CURRENCY: "USD"

args:
  - connectors
  - list

resources: {}
