apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: finsre
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: finsre-runtime
          maxRetries: 1
          containers:
            - image: REPLACE_WITH_IMAGE
              env:
                - name: FINSRE_ENVIRONMENT
                  value: cloudrun
                - name: FINSRE_GCP_BILLING_ACCOUNT
                  value: REPLACE_WITH_BILLING_ACCOUNT_ID
                - name: FINSRE_GCP_BILLING_CURRENCY
                  value: USD
              args:
                - connectors
                - list
