apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finsre
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      serviceAccountName: finsre-runtime
      containers:
        - image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: FINSRE_ENVIRONMENT
              value: cloudrun
            - name: FINSRE_GCP_BILLING_TABLE
              value: REPLACE_WITH_PROJECT.DATASET.TABLE
            - name: FINSRE_GCP_BILLING_PROJECT
              value: REPLACE_WITH_PROJECT
